//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomDatabaseTraceListener.Configuration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DesignResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DesignResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CustomDatabaseTraceListener.Configuration.DesignResources", typeof(DesignResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the stored procedure in the database that creates a new Category in the tables. 
        ///The default is &apos;AddCategory&apos; and is created by the scripts you can run to create the logging database..
        /// </summary>
        internal static string CustomDatabaseTraceListenerDataAddCategoryStoredProcNameDescription {
            get {
                return ResourceManager.GetString("CustomDatabaseTraceListenerDataAddCategoryStoredProcNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Category Procedure.
        /// </summary>
        internal static string CustomDatabaseTraceListenerDataAddCategoryStoredProcNameDisplayName {
            get {
                return ResourceManager.GetString("CustomDatabaseTraceListenerDataAddCategoryStoredProcNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the Database Instance to use for logging messages, as configured in the Data Access Application Block..
        /// </summary>
        internal static string CustomDatabaseTraceListenerDataDatabaseInstanceNameDescription {
            get {
                return ResourceManager.GetString("CustomDatabaseTraceListenerDataDatabaseInstanceNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Instance.
        /// </summary>
        internal static string CustomDatabaseTraceListenerDataDatabaseInstanceNameDisplayName {
            get {
                return ResourceManager.GetString("CustomDatabaseTraceListenerDataDatabaseInstanceNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A logging target listener that sends log messages to a specified database using a database instance configured in the Data Access Application Block..
        /// </summary>
        internal static string CustomDatabaseTraceListenerDataDescription {
            get {
                return ResourceManager.GetString("CustomDatabaseTraceListenerDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Database Trace Listener.
        /// </summary>
        internal static string CustomDatabaseTraceListenerDataDisplayName {
            get {
                return ResourceManager.GetString("CustomDatabaseTraceListenerDataDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum severity of messages that will be sent to the logging target. 
        ///Valid values are All (the default), Off, Critical, Error, Warning, Information, Verbose, and Activity Tracing. 
        ///The behavior is for messages with the selected severity and all higher severities to be included. 
        ///For example, the Warning setting will allow warning, error, and critical messages to be written to the logging target..
        /// </summary>
        internal static string CustomDatabaseTraceListenerDataFilterDescription {
            get {
                return ResourceManager.GetString("CustomDatabaseTraceListenerDataFilterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severity Filter.
        /// </summary>
        internal static string CustomDatabaseTraceListenerDataFilterDisplayName {
            get {
                return ResourceManager.GetString("CustomDatabaseTraceListenerDataFilterDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the Log Message Formatter to use to format log messages written to the database..
        /// </summary>
        internal static string CustomDatabaseTraceListenerDataFormatterDescription {
            get {
                return ResourceManager.GetString("CustomDatabaseTraceListenerDataFormatterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatter.
        /// </summary>
        internal static string CustomDatabaseTraceListenerDataFormatterDisplayName {
            get {
                return ResourceManager.GetString("CustomDatabaseTraceListenerDataFormatterDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fully qualified type name of the Listener..
        /// </summary>
        internal static string CustomDatabaseTraceListenerDataListenerDataTypeNameDescription {
            get {
                return ResourceManager.GetString("CustomDatabaseTraceListenerDataListenerDataTypeNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listener Data Type.
        /// </summary>
        internal static string CustomDatabaseTraceListenerDataListenerDataTypeNameDisplayName {
            get {
                return ResourceManager.GetString("CustomDatabaseTraceListenerDataListenerDataTypeNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the Custom Database Trace Listener..
        /// </summary>
        internal static string CustomDatabaseTraceListenerDataNameDescription {
            get {
                return ResourceManager.GetString("CustomDatabaseTraceListenerDataNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string CustomDatabaseTraceListenerDataNameDisplayName {
            get {
                return ResourceManager.GetString("CustomDatabaseTraceListenerDataNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listeners that do not output to a Text Formatter use this property to determine which options, or elements, should be included in the trace output. 
        ///Possible values are: CallStack, DateTime, LogicalOperationStack, None, ProcessId, ThreadId, and Timestamp. The default is None. This property is optional..
        /// </summary>
        internal static string CustomDatabaseTraceListenerDataTraceOutputOptionsDescription {
            get {
                return ResourceManager.GetString("CustomDatabaseTraceListenerDataTraceOutputOptionsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trace Output Options.
        /// </summary>
        internal static string CustomDatabaseTraceListenerDataTraceOutputOptionsDisplayName {
            get {
                return ResourceManager.GetString("CustomDatabaseTraceListenerDataTraceOutputOptionsDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fully qualified type name of the Custom Database Trace Listener..
        /// </summary>
        internal static string CustomDatabaseTraceListenerDataTypeNameDescription {
            get {
                return ResourceManager.GetString("CustomDatabaseTraceListenerDataTypeNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string CustomDatabaseTraceListenerDataTypeNameDisplayName {
            get {
                return ResourceManager.GetString("CustomDatabaseTraceListenerDataTypeNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the stored procedure in the database that writes log messages into the tables. 
        ///The default is &apos;WriteLog&apos;, and is created by the scripts you can run to create the logging database..
        /// </summary>
        internal static string CustomDatabaseTraceListenerDataWriteLogStoredProcNameDescription {
            get {
                return ResourceManager.GetString("CustomDatabaseTraceListenerDataWriteLogStoredProcNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write To Log Procedure.
        /// </summary>
        internal static string CustomDatabaseTraceListenerDataWriteLogStoredProcNameDisplayName {
            get {
                return ResourceManager.GetString("CustomDatabaseTraceListenerDataWriteLogStoredProcNameDisplayName", resourceCulture);
            }
        }
    }
}
